<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0; }
        .container { width: 90%; margin: auto; padding: 20px; }
        
        /* Header */
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            font-size: 24px;
            color: #4a90e2;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 14px;
            color: #666;
        }

        /* Divider */
        .divider {
            border-top: 2px solid #4a90e2;
            margin: 20px 0;
        }

        /* Chart */
        .chart {
            text-align: center;
            margin-bottom: 30px;
        }

        /* Table Styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #4a90e2;
            color: #fff;
            padding: 10px;
            font-size: 14px;
        }
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
            font-size: 12px;
        }
        tr:nth-child(even) { background-color: #f9f9f9; }

        /* Footer */
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <h1>Data Trend Report</h1>
        </div>
        
        <!-- Chart Image -->
        <div class="chart">
            <img src="{{ $quickChartUrl }}" alt="Data Trend Chart" style="max-width: 100%; height: auto;">
        </div>

        <div class="divider"></div>

        <!-- Data Summary Tables -->
        <h2>Data Summary</h2>

        <h3>Payments</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Payments</th>
                </tr>
            </thead>
            <tbody>
                @foreach($paymentData as $date => $total)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ $total }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h3>Order Member</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Orders</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orderData as $date => $total)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ $total }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h3>Order Complement</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Complements</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orderComplementData as $date => $total)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ $total }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h3>Users</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Users</th>
                </tr>
            </thead>
            <tbody>
                @foreach($userData as $date => $total)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ $total }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <h3>Members</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Total Members</th>
                </tr>
            </thead>
            <tbody>
                @foreach($memberData as $date => $total)
                <tr>
                    <td>{{ $date }}</td>
                    <td>{{ $total }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Footer -->
        <div class="footer">
            <p>Generated by {{ $app->app_name }} on {{ now()->format('d M Y H:i:s') }}</p>
        </div>
    </div>
</body>
</html>
